language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer install --dev --no-interaction --prefer-source

script:
    - vendor/bin/php-cs-fixer fix -v --dry-run src/
    - vendor/bin/phpunit -c phpunit.xml.dist --colors --coverage-clover=build/logs/clover.xml

before_script:
    - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
