language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer install --dev --no-interaction --prefer-source

script:
    - vendor/bin/php-cs-fixer fix -v --dry-run src/
    - vendor/bin/phpunit -c phpunit.xml.dist
